<?php /** 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://beta.skaffolder.com/#!/register?friend=5ca6fb6b3e3a575750171757
*
* You will get 10% discount for each one of your friends
* 
*/
?>
<?php
	require_once './db/dbUAOT_dbManager.php';
	
/*
 * SCHEMA DB FindJob
 * 
	{
		JobField: {
			type: 'String'
		},
		JobLocation: {
			type: 'String'
		},
		JobTitle: {
			type: 'String'
		},
		NoNeed: {
			type: 'Number'
		},
		//RELAZIONI
		
		
		//RELAZIONI ESTERNE
		
		
	}
 * 
 */


//CRUD METHODS


//CRUD - CREATE


$app->post('/findjob',	function () use ($app){

	$body = json_decode($app->request()->getBody());
	
	$params = array (
		'JobField'	=> isset($body->JobField)?$body->JobField:'',
		'JobLocation'	=> isset($body->JobLocation)?$body->JobLocation:'',
		'JobTitle'	=> isset($body->JobTitle)?$body->JobTitle:'',
		'NoNeed'	=> isset($body->NoNeed)?$body->NoNeed:'',
			);

	$obj = makeQuery("INSERT INTO findjob (_id, JobField, JobLocation, JobTitle, NoNeed )  VALUES ( null, :JobField, :JobLocation, :JobTitle, :NoNeed   )", $params, false);

	
	echo json_encode($body);
	
});
	
//CRUD - GET ONE
	
$app->get('/findjob/:id',	function ($id) use ($app){
	$params = array (
		'id'	=> $id,
	);
	
	$obj = makeQuery("SELECT * FROM findjob WHERE _id = :id LIMIT 1", $params, false);
	
	
	
	echo json_encode($obj);
	
});
	

//CRUD - EDIT

$app->post('/findjob/:id',	function ($id) use ($app){

	$body = json_decode($app->request()->getBody());
	
	$params = array (
		'id'	=> $id,
		'JobField'	    => isset($body->JobField)?$body->JobField:'',
		'JobLocation'	    => isset($body->JobLocation)?$body->JobLocation:'',
		'JobTitle'	    => isset($body->JobTitle)?$body->JobTitle:'',
		'NoNeed'	    => isset($body->NoNeed)?$body->NoNeed:''	);

	$obj = makeQuery("UPDATE findjob SET  JobField = :JobField,  JobLocation = :JobLocation,  JobTitle = :JobTitle,  NoNeed = :NoNeed   WHERE _id = :id LIMIT 1", $params, false);

	
	echo json_encode($body);
    	
});


/*
 * CUSTOM SERVICES
 *
 *	These services will be overwritten and implemented in  Custom.js
 */

			
?>